kind: pipeline
name: default

steps:
 - name: test
   image: rust:1.34.0
   environment:
    CARGO_HOME: /drone/.cargo
   commands:
    - cargo test
 - name: fmt
   image: rust:1.34.0
   environment:
    CARGO_HOME: /drone/.cargo
   commands:
    - rustup component add rustfmt
    - cargo fmt -- --check
 - name: clippy
   image: rust:1.34.0
   environment:
    CARGO_HOME: /drone/.cargo
   commands:
    - rustup component add clippy
    - cargo clippy
